// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npaegnxizwnovfcmdnrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wYWVnbnhpendub3ZmY21kbnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDgyODMsImV4cCI6MjA2NzA4NDI4M30.4lrx3L2CnNRAy71U8XeRI2x5RQQ12FrfzC4DSt2ESC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});